import { Center, useAnimations, useGLTF } from '@react-three/drei';
import { Canvas } from '@react-three/fiber';
import { useEffect } from 'react';

/*
  Title: DANCING STORMTROOPER
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Author: StrykerDoesAnimation (https://sketchfab.com/strykerdoesgames)
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Source: https://sketchfab.com/3d-models/dancing-stormtrooper-12bd08d66fe04a84be446e583d6663ac
*/
function StormTrooper() {
  const { nodes, materials, animations } = useGLTF('/3d-models/StormTrooper.glb');
  const { ref, actions } = useAnimations(animations);

  useEffect(() => {
    actions['mixamo.com']!.play();
  }, [actions]);

  return (
    <group name='Sketchfab_Scene' ref={ref} dispose={null}>
      <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
        <group name='f8ce42897676455090b6ff376356f84cfbx' rotation={[Math.PI / 2, 0, 0]}>
          <group name='Object_2'>
            <group name='RootNode'>
              <group name='Object_4'>
                <primitive object={nodes._rootJoint} />
                <skinnedMesh
                  castShadow
                  name='Object_7'
                  geometry={nodes.Object_7.geometry}
                  skeleton={nodes.Object_7.skeleton}
                  material={materials.Stormtroopermat}
                ></skinnedMesh>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default function Playground() {
  return (
    <Canvas camera={{ position: [0, 0, 8], fov: 40 }} style={{ width: '100%', height: '100%' }}>
      {/* Generic and simple diffusion lighting */}
      <ambientLight />
      {/* Studio-like lighting (top-left-behind, top-right-behind, refractive light on the bottom) */}
      <directionalLight position={[1, 4, 0]} intensity={1} />
      <directionalLight position={[-1, 4, 0]} intensity={1} />
      <directionalLight position={[4, -6, -4]} intensity={1} />
      {/* Simple iPhone X model with looped video as the screen material */}
      <Center>
        <StormTrooper />
      </Center>
    </Canvas>
  );
}
